# https://sha.ws/automatic-upload-to-google-cloud-storage-with-github-actions.html

name: GSP - Push Repo # name of your workflow
on:
  push:
    branches:
      - master # Deployment will be triggered when we will push to the master branch

env: GCS_BUCKET: ${{ secrets-GCS_BUCKET }}

steps:
- name: Checkout
    uses: actions/checkout@v2

- name: Setup - gcloud / gsutil
  uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
  with:
    service_account_key: ${{ secrets.GCS_SA_KEY }}
    project_id: ${{ secrets.GCS_PROJECT }}
    export_default_credentials: true

- name: Deploy
  run: |-
    gsutil -m rsync -R output gs://$GCS_BUCKET