# https://sha.ws/automatic-upload-to-google-cloud-storage-with-github-actions.html

name: GSP - Push Repo # name of your workflow
on:
  push:
    branches:
      - master # Deployment will be triggered when we will push to the master branch

env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}

jobs:
  push-to-gcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/auth@v0
        with:
          service_account: "${{ secrets.GCP_SA_EMAIL }}"
          credentials_json: "a2bbd2ccbfa1aa70667837ca3d24a970e7ba9874"
      - uses: google-github-actions/setup-gcloud@v0
      - run: gsutil -m rsync -R output gs://$GCS_BUCKET
